[package]
name = "tint2-bars"
version = "0.1.0"
authors = ["Duong Do Minh Chau <duongdominhchau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0"
signal-hook = "0.3"
zbus = { version = "2.0.0-beta.2", features = ["serde-xml-rs"] }
serde = { version = "1.0", features = ["derive"] }
zvariant = "2.5.0"
thiserror = "1.0"
